export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkdsYXVjaW8gRGFuaWVsIiwiZW1haWwiOiJnbGF1Y2lvMkBoY29kZS5jb20uYnIiLCJpYXQiOjE3MjYxNjUzMDgsImV4cCI6MTcyNjc3MDEwOCwiYXVkIjoidXNlcnMiLCJpc3MiOiJsb2dpbiIsInN1YiI6IjIifQ.riUWk8szxJR1tTpy3i3mKWctuJadGkcT8IUzcyhIhW8';
